version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/solarwatch
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: bence
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  db:
    image: 'postgres:15-alpine'
    container_name: postgres-db
    environment:
      POSTGRES_DB: solarwatch
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bence
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
